[project]
authors = ["Surfer12 <ryanoatsie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "rcct"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
anthropic = ">=0.49.0,<0.50"
